version: "3.8"
services:
  mysql:
    image: mariadb:10.8.3
    container_name: cuillere_app_mysql
    volumes:
      - database_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  database_data: ~

networks:
  default: